version: '3.4'

services:
  wifianalyzermqtt:
    image: wifianalyzermqtt
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development 
      mqttHost: 'mqtt://host'
      mqttTopic: 'topic/'
      mqttUserName: ''
      mqttPassword: '' 
